env:
  global:
  - secure: u1Jmf3eRjmE/9H+RLwxMvZze2mhKEE4lp7vQ9/Y5GQKCoxgeXAnvIYBd+JjM257rHAigIpmIVUUA+tPK9hCFAfcNbNmR3IzDLPatAFd7JyuuIIJJmX/cvBw4hhrxJ4LkavEmijXtDiQPkGNpGSVWPx4TVVen4Yhk8S+OgxqX9lSuv7JZE91p6o6Wykr7uzMk2rD20vP2LzFAPYOjpjap0BmbQu+qoTTya/NM2xEn88lzv+xpR7zElMg7EZMgVVRMZl0W2uLxF1RLIcKs5JWeqW5LPG0PD2M3sY/BnoYsLNrzVzN2JOnIZQHDs6hXnDAcRkYdpiIDn+95Klw3ammPXsOs9I8kUiclSlyvOutsQ2d6lgamxolDVlcq/CszKdfA+jwz6xUZc2T3KZ1owPrJiUeuYHpm0NGLllEUhM5Ois0iqSNO+GRAYNeJGcZoXUL2EJ6zOUUZk6F+53HeaWrTFizjZzxKEs2Azjwo/rgaAgGOOWjhNI0rcctQM+jOibJVer5Dy8gJ+rQ1J2emb+Nsz40mwVYIM+6jiGO/ckuV8tRhRfhidCx8YITbS9Vul04cxg+6PX979ES3r9Ss7IoBCpuqTEYwDw/kv6UYIGKTVFuG8b2MkpPsUmniL9o85TEanERr6NN5f95oQumiQWwNglQNGhJGzqvo2UjG92RClUY=
  - secure: 6RJLiFpV6KzYsOpAf0lbnMxci09nDYXxINm4k5voTrq9i2qrcdbkbSKEWgJ477Tj9jOmIG4efcIwcbvo7eRMFeLwI9+V0o8ewAk//C9FyWFgKLthq8VzBMiwiRA4bWoSxMrvgixoZgfKNAUNvVXuaWI+R0x7Ag3p9oUWX5IwWBmucLai2TMJtbnVPJGoe2pIyAgj8CgGnYsMY9CYZsf1YgzrCULbGZ8cMz2sBdBcAH10JJmuwmSd6kgUR9yZc5yLsNkVhoq1KSi711rvFDXk5YpYVsVuayrziDqMFTJRSHKz74DtF6EzKFTGi+eWb/FcgF5bKdkuPuFLtTDTHzLiEZ3RjzF8GaEXKEGR1Sh3p57lFJIfNZYKHQXFPdT4Ir/0CI3dm7DJIm3m/HDDCcpy8NxPhKW7dfa5xkptqmiHLgjXqU5LXeY5/rlV5RHsgPzm2zDJH9n2KkaRxMmU3olJ2uNK6clraHk+CceJkeT/1UXQDig5DdAvG/+rvRwLsTwpUhAcxOJ0v/JUTAJePK7A2Z/RsMTILm0dg8FdjB8qmgPr59s6oN1UjchV9UBUi2Ofsw09piSFaXZVmQxBqR02J5CHtsVT+y4OE1BeueFJqVf3GAUmQxBmoKFepwWf9gYTLssEjF3Sypl9Bo8C+ar412g0LcVWYqm0R4SxiEug4xI=
  - COMMIT=${TRAVIS_COMMIT::8}

services:
  - docker
  
install: true

script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=updatehub/qemu-runner
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
