#!/bin/sh
# Copyright (C) 2017 O.S. Systems Sofware LTDA
#
# SPDX-License-Identifier:     GPL-2.0
#
# NOTE: current settings forward
#   ssh: port 8822
#   serial console: stdio

set -e

ARCH=$1
IMAGE=$2
MAC=$3

[ -n "$MAC" ] || MAC="52:54:00$(od -txC -An -N3 /dev/urandom|tr \  :)"

export QEMU_AUDIO_DRV=none

case "${ARCH}" in
    arm)
    tar -C /tmp -x -f ${IMAGE}

    qemu-system-arm \
         -M vexpress-a9 \
         -m 128M \
         -kernel /tmp/u-boot.elf \
         -drive file=/tmp/nor0,if=pflash,format=raw \
         -drive file=/tmp/nor1,if=pflash,format=raw \
         -net nic,macaddr=${MAC} \
         -net user,hostfwd=tcp::22-:22 \
         -nographic

    tar -C /tmp -c u-boot.elf nor0 nor1 -f ${IMAGE}
    rm /tmp/u-boot.elf /tmp/nor0 /tmp/nor1
    ;;
    i386)
    exec qemu-system-i386 \
         -M pc \
         -m 128M \
         -drive if=pflash,format=raw,readonly,file=/usr/share/ovmf/ovmf_code_ia32.bin \
         -drive if=ide,format=raw,file=${IMAGE} \
         -net nic,macaddr=${MAC} \
         -net user,hostfwd=tcp::22-:22 \
         -nographic
    ;;
    x86-64)
    exec qemu-system-x86_64 \
         -cpu qemu64,+ssse3 \
         -m 128M \
         -drive if=pflash,format=raw,readonly,file=/usr/share/ovmf/ovmf_code_x64.bin \
         -drive if=pflash,format=raw,file=/usr/share/ovmf/ovmf_vars_x64.bin \
         -drive if=virtio,format=raw,file=${IMAGE} \
         -net nic,macaddr=${MAC} \
         -net user,hostfwd=tcp::22-:22 \
         -nographic
    ;;
    *)
    echo "ERROR: Unknown ARCH value. Valid ones are: arm, i386 or x86-64"
    exit 1
    ;;
esac
