#!/bin/sh
# NOTE: current settings forward
#   ssh: port 8822
#   serial console: stdio

set -e

IMAGE=$1
MAC=$2

[ -n "$MAC" ] || MAC="52:54:00$(od -txC -An -N3 /dev/urandom|tr \  :)"

export QEMU_AUDIO_DRV=none

exec qemu-system-x86_64 \
    -cpu qemu64,+ssse3 \
    -m 512M \
	-drive if=pflash,readonly,file=/usr/share/ovmf/bios.bin \
	-drive if=virtio,format=raw,file=${IMAGE} \
    -net nic,macaddr=${MAC} \
    -net user,hostfwd=tcp::22-:22 \
	-nographic
